name: event-suppressor
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - numpy
  - h5py
  - scipy
  - pyyaml
  - tqdm
  - pip:
      - hdf5plugin
      - opencv-python
      - albumentations
      - -e ./ev-loader
      - -e .
